# Github actions workflow name
name: VSCode Test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  VSCode-Test:
    name: 'CI on ${{matrix.os}} with node14'
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
         cache: 'yarn'
      - run: yarn install
      - run: yarn test
      
